### ISSUE TITLE
Request others files

### ISSUE THREAD

**Issue by luigi8bits** [lukeshondas/Dell-Latitude-5290-Opencore#1]
Hi @lukeshondas,

Could you please provide the complete files from the "OC" folder (ACPI, drivers, etc.)?

Thanks!

**Comment by lukeshondas** [comment]
Hey, the complete OC folder can be found inside the zipped download under Releases. All downloads contain the same OC folder other than the config file.

**Comment by luigi8bits** [comment]
Ohhhh my fault, You're the best! Thanks so much for sharing it with us!
